"""
Validation Models

Defines data structures for validation results, issues, and recommendations
returned by the rules engine.
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional
from enum import Enum


class IssueSeverity(str, Enum):
    """Severity levels for validation issues"""
    ERROR = "error"      # Critical issue, timeline cannot proceed
    WARNING = "warning"  # Significant issue, should be addressed
    INFO = "info"        # Informational, suggestion for improvement


class IssueCategory(str, Enum):
    """Categories of validation issues"""
    REGULATORY = "regulatory"
    DURATION = "duration"
    DEPENDENCIES = "dependencies"
    CHECKLISTS = "checklists"
    OPERATIONAL = "operational"
    PARALLELIZATION = "parallelization"
    RISK = "risk"


class ValidationIssue(BaseModel):
    """
    Represents a single validation issue found in a timeline

    Issues are generated by validators and include:
    - What the problem is
    - Why it's a problem
    - How to fix it
    """
    rule_id: str = Field(..., description="Unique identifier for the validation rule")
    severity: IssueSeverity = Field(..., description="Severity level")
    category: IssueCategory = Field(..., description="Issue category")

    task_id: Optional[str] = Field(None, description="ID of task with issue (if applicable)")
    task_name: Optional[str] = Field(None, description="Name of task with issue")

    message: str = Field(..., description="Short description of the issue")
    detail: str = Field(..., description="Detailed explanation of why this is an issue")
    suggested_fix: str = Field(..., description="Recommended action to resolve the issue")

    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence in this issue (0-1)")

    # Reference information
    regulatory_reference: Optional[str] = Field(None, description="Regulatory citation if applicable")
    evidence: List[str] = Field(default_factory=list, description="Evidence or examples")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "rule_id": "REG-GATE-001",
                "severity": "error",
                "category": "regulatory",
                "task_id": None,
                "message": "Missing required regulatory gate: IND Submission",
                "detail": "FDA requires IND Submission gate before patient enrollment. This is a blocking regulatory requirement.",
                "suggested_fix": "Add 'IND Submission' task with 60 days duration before First Patient In",
                "confidence": 1.0,
                "regulatory_reference": "21 CFR 312.20"
            }
        }
    )


class ValidationStatus(str, Enum):
    """Overall validation status"""
    PASSED = "passed"      # No errors, may have warnings/info
    WARNINGS = "warnings"  # Has warnings but no errors
    FAILED = "failed"      # Has critical errors


class ValidationResult(BaseModel):
    """
    Complete validation result for a timeline

    Returned by the /api/v1/validate endpoint
    """
    status: ValidationStatus = Field(..., description="Overall validation status")
    issues: List[ValidationIssue] = Field(default_factory=list, description="List of validation issues")

    # Summary counts
    error_count: int = Field(default=0, ge=0, description="Number of errors")
    warning_count: int = Field(default=0, ge=0, description="Number of warnings")
    info_count: int = Field(default=0, ge=0, description="Number of info items")

    total_tasks_analyzed: int = Field(..., ge=0, description="Total number of tasks analyzed")
    validators_run: List[str] = Field(default_factory=list, description="List of validators that were executed")

    # Timing
    validation_duration_ms: Optional[int] = Field(None, description="Time taken for validation in milliseconds")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "status": "warnings",
                "issues": [
                    {
                        "rule_id": "DUR-001",
                        "severity": "warning",
                        "category": "duration",
                        "task_id": "T003",
                        "task_name": "IRB Approval",
                        "message": "Duration too short: IRB Approval",
                        "detail": "Task duration (15 days) is below minimum (21 days)",
                        "suggested_fix": "Increase duration to at least 21 days",
                        "confidence": 0.85
                    }
                ],
                "error_count": 0,
                "warning_count": 1,
                "info_count": 0,
                "total_tasks_analyzed": 15,
                "validators_run": ["Regulatory Gating", "Duration Bounds"]
            }
        }
    )


class Recommendation(BaseModel):
    """
    Represents a recommendation for timeline improvement

    Recommendations are suggestions that aren't necessarily issues,
    but opportunities for optimization.
    """
    recommendation_id: str = Field(..., description="Unique recommendation identifier")
    type: str = Field(..., description="Type of recommendation")

    task_ids: List[str] = Field(default_factory=list, description="Tasks affected by this recommendation")
    title: str = Field(..., description="Short title")
    description: str = Field(..., description="Detailed description")
    benefit: str = Field(..., description="Expected benefit if implemented")

    impact_days: Optional[int] = Field(None, description="Potential time savings in days")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence in this recommendation")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "recommendation_id": "PAR-001",
                "type": "parallelization",
                "task_ids": ["T005", "T006"],
                "title": "Parallelize site contracts and IRB submissions",
                "description": "Tasks 'Site Contract Execution' and 'Central IRB Submission' have no dependencies and can run in parallel",
                "benefit": "Could save approximately 30 days on critical path",
                "impact_days": 30,
                "confidence": 0.9
            }
        }
    )
